### ISSUE TITLE
Call destroy_all after 'where' to has_many associated member , ArgumentError has raised.

### ISSUE THREAD

**Issue by syguer** [alfa-jpn/kakurenbo#16]
Hi.
I"m using this gem instead of acts as paranoid on Rails 4.1.7.
This gem is very useful, Thanks:)

By the way,  I found the issue on calling destroy_all after 'where'.
You can reproduce this issue on this [repo](https://github.com/syguer/sandbox_kakurenbo_bugfix).
And I've created a patch to avoid this issue.
Please check it.

Regards.

P.S
I think this patch looks bad resolver because it can't do exhaustive test and lose maintenability.
It might be hard way that adding options to argument...

**Comment by nabetaro** [comment]
I had same problem.
That patch work fine in my app.

Thanks to great gem and great patch!

**Comment by alfa-jpn** [comment]
Sorry for the late reply.
Thanks for great PR!
